version: '3.7'

services:

  backend_node:
    container_name: backend_node
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev

    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3003:3003